#!/usr/bin/python3

import sys

def factorize(n):
    factors = []
    i = 2
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

input_file = sys.argv[1]

try:
    with open(input_file, "r") as file:
        for line in file:
            num = int(line)
            factors = factorize(num)
            if len(factors) == 2:
                p, q = factors
                print(f"{num}={p}*{q}")
            else:
                for i in range(2, num + 1):
                    if num % i == 0:
                        p = i
                        q = num // i
                        print(f"{num}={p}*{q}")
                        break
except FileNotFoundError:
    print(f"File '{input_file}' not found.")
except ValueError:
    print("Invalid input in the file. Make sure all lines are valid natural numbers greater than 1.")
